### ISSUE TITLE
[Investigate] Auto discover for balances

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#1669]
Let us investigate how to reliably and correctly auto discover all chains and tokens, without the need to manually adding them.

**Comment by johnnyluo** [comment]
@enriquesouza we use alchemy api for solana/base/arbitrum right now , can you please investigate whether we can use alchemy api to do token discovery?

**Comment by johnnyluo** [comment]
We could use `alchemy_getTokenBalances`

**Comment by enriquesouza** [comment]
Cool. LGTM, lets use this one

**Comment by enriquesouza** [comment]
@realpaaao @johnnyluo I would hold this a bit since we are discovering tokens using RPCs, so since we migrated this week the RPCs to Alchemy it should Also fix itself bc we won't have rate limits. So maybe we don't need to change it now. Unless the token metadata is causing the issue. So we can use

https://docs.alchemy.com/reference/alchemy-gettokenmetadata

I think we can use it.
