### ISSUE TITLE
[Main screen] Total balance sometimes more than expected

### ISSUE THREAD

**Issue by flypaper0** [vultisig/vultisig-ios#480]
**Describe the bug**
I cannot reproduce right now, but see it second time. Looks like one of coins counting twice sometimes

**Comment by oxyc** [comment]
for me it’s still consistently reproducible with https://github.com/vultisig/vultisig-ios/issues/401#issue-2279877626

**Comment by realpaaao** [comment]
Also was able to reproduce and caused by Rune and Maya chains being activated. 
When one or both chains are active it is possible to have RUNE or CACAO balance counted double:
- mainly caused by adding/removing tokens of chains
- Having activated tokens on MAYA and ETH
- removing or adding tokens on ETH chain (higher probaility when adding multiple tokens at once)
- sometimes possible to recreate when adding/removing tokens on other chains.

Also when toggeling chains or tokens, total balance is not updated automatically and need to enter detailview to update total balance. 

- [ ] Refresh total balance on swipe up.

**Comment by enriquesouza** [comment]
We fixed that.
