### ISSUE TITLE
[ADD] Check for input on deposit view before continue

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#566]
**Is your feature request related to a problem? Please describe.**
At the moment it is possible to continue on `message deposit view` without or incorrect input.

**Describe the solution you'd like**
Check for following input in text fields:
- [x] Amount: only positive, on Mac negative numbers are possible.
- [x] Node address: only viable address format for respective chain
- [x] Provider: having description `optional` as a placeholder and checking for correct address format
- [x] Fee: having description `optional` as a placeholder and only positive numbers

if not, prompt user error message to complete missing or bad input.

**Comment by enriquesouza** [comment]
Regarding the amount field, it is highly unlikely that users will enter a negative number for the bond, especially since we already use a numeric keypad to input the amount. Therefore, this scenario should not occur. Moreover, implementing this kind of validation would significantly increase the complexity of the deposit process due to its dynamic nature.

The node address is already being validated for Thor and Maya.
