### ISSUE TITLE
[BUG] Check message deposit view input

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#640]
On mac it is still possible to input letters and symbols in the `Operator's Fee` text field. Please also implement a check.

**Comment by enriquesouza** [comment]
Oh, this is not an issue, because it only accepts numbers in the field, if you type alpha it will convert back to zero. In the next screen, it will not appear. The user should know also the should but numbers as well. 

step 1 (type anything):
<img width="1032" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/1700699/e758f505-6254-47c4-b184-5bbaefd49fbd">

We don't accept it anyway. So the user is really forcing an error.

<img width="1031" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/1700699/da3d9af7-f8d7-495d-bd51-9c516481f110">

Now if they put it correctly then it is fine:
<img width="1034" alt="image" src="https://github.com/vultisig/vultisig-ios/assets/1700699/a4a3dcdb-f6da-4585-86b7-45f3a3bf2541">

**Comment by enriquesouza** [comment]
I've added a validation, so if the provider is not empty then the fee should be greater than zero. It will be published in the next PR.
