### ISSUE TITLE
[BUG] Going back on keygen/keysign summary

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vultisig-ios#797]
**Describe the bug**
When preparing a keygen or keysign with the initiating device and revising information in the `Summary view`. If deciding to go back to select the pairing devices, it jumps one view more than intended. In Keygen to `name vault View` and on Keysign to `Setup View`.

**To Reproduce**
1. Go to `Summary view` on keygen/keysign
2. pressing on back button

**Expected behavior**
Just go one step, back to the pairing view, so user can select which devices that already joined.

-v35

**Comment by johnnyluo** [comment]
The reason it doesn't go back to peer discovery device selection view is because they are the same view. PeerDiscovery / Keygen summary are actually on the same screen. 

We build in the feature to automatically select peer , and automatically start keysign to make sure user don't need to manually select it. 

This issue is  contradict to the auto select feature we have. 

If we really want to let user to change it , let's add a change button to flip the status back to peer discovery and don't change the behaviour of back button

For Keysign , we should not change it ,  because first of all keysign doesn't have summary view , and when keysign started , peer discovery is already finished, so user should start peer discovery again , going back to verify page is correct

**Comment by realpaaao** [comment]
@johnnyluo ok in that case let's leave it. It is just a small observation I made and will not really impact UX.
closing
