### ISSUE TITLE
VAULT SHARE ISSUE - hex code ends

### ISSUE THREAD

**Issue by jpthor** [vultisig/vultisig-ios#840]
https://github.com/vultisig/airdrop-registry/issues/2#issue-2392579456

**Comment by johnnyluo** [comment]
The public key is correct , and valid

1.EdDSA (Edwards Curve Digital Signature Algorithm): For EdDSA, particularly when using Curve25519 or Ed25519, the public key is represented by a single coordinate (the (x) coordinate for Curve25519, and the (y) coordinate for Ed25519), because the other coordinate can be deterministically computed from it. The public key is typically 32 bytes long when serialized because it only needs to store one 256-bit coordinate.  
2.ECDSA (Elliptic Curve Digital Signature Algorithm): In ECDSA, when public keys are compressed, they include one coordinate (either (x) or (y)) and an additional byte to indicate which of the two possible (y) coordinates is the correct one (since for every (x) value there are two possible (y) values). This is why compressed ECDSA public keys are 33 bytes long: 32 bytes for the coordinate and 1 byte for the indication of the (y) coordinate.
